### ISSUE TITLE
FLANN errors on 64bit MSVC2010 (debug)

### ISSUE THREAD

**Issue by chambbj** [chambbj/osgeo-superbuild#3]
Recommended fix at https://github.com/mariusmuja/flann/issues/82 (i.e., adding the following to `serialization.h`)

```
#ifdef _MSC_VER
BASIC_TYPE_SERIALIZER(unsigned __int64);
#endif
```

does not seem to work (it is implemented as a patch step). We still get:

```
C:\Users\chambersbj\Documents\dev\osgeo-superbuild\build\nmake64\flann\src\flann\src\cpp\flann/util/serialization.h(22) : error C2228: left of '.serialize' must have class/struct/union
        type is 'unsigned __int64'
```

**Comment by kwaegel** [comment]
The #ifdef patch seems to fix this particular error on MSVC 2012 64-bit (using release 1.8.4).

**Comment by chambbj** [comment]
Confirmed. I had a typo last time I tried this.

**Comment by bjoernkrueger** [comment]
Hi, I'm currently facing the same problem, could you give a hint where these additional lines of codes have to be added in the serialization.h ?

**Comment by kwaegel** [comment]
Right below the other BASIC_TYPE_SERIALIZER(...) statements. Should be somewhere around line #94.

**Comment by dbarash1** [comment]
Thanks kwaegel, it helped fix my build as well.
